INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Arthur Sicard', 3, 'arthur2rennes@hotmail.fr', 646692204, 'undeuxtrois');
INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Mathilde Juillet', 3, 'mathilde.juillet@isen-bretagne.fr', 646692204, 'sept');
INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Max Buridant', 1, '', NULL, 'lol');
INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Benjamin Binard', 1, '', NULL, 'blender');
INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Steven Corre', 2, 'arthur.sicard@isen-bretagne.fr', 646692204, 'styff');
INSERT INTO UTILISATEUR (NOM_UTILISATEUR, TYPE_UTILISATEUR, CONTACT_MAIL, CONTACT_SMS, PASSWORD) VALUES ('Tyff Tyff', 2, 'arthur2rennes@gmail.com', 646692204, 'bb-8');

INSERT INTO SUPERVISE (ID_UTILISATEUR, UTI_ID_UTILISATEUR) VALUES (1, 4);
INSERT INTO SUPERVISE (ID_UTILISATEUR, UTI_ID_UTILISATEUR) VALUES (2, 3);
INSERT INTO SUPERVISE (ID_UTILISATEUR, UTI_ID_UTILISATEUR) VALUES (5, 3);
INSERT INTO SUPERVISE (ID_UTILISATEUR, UTI_ID_UTILISATEUR) VALUES (6, 4);

INSERT INTO LIEU (NOM_LIEU) VALUES ('Rennes Living Lab');
INSERT INTO LIEU (NOM_LIEU) VALUES ('Brest Living Lab');

INSERT INTO QUI (ID_LIEU, ID_UTILISATEUR) VALUES (1, 3);
INSERT INTO QUI (ID_LIEU, ID_UTILISATEUR) VALUES (1, 4);

INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, NULL, 27, 16, 1, 2);
INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, 1500, 1200, NULL, 5, 1);
INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, NULL, 75, 35, 1, 3);
INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, NULL, 2, NULL, 3, 4);
INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, NULL, NULL, NULL, 4, 5);
INSERT INTO ALERTES (ID_LIEU, SEUIL_CRITIQUE, SEUIL_HAUT, SEUIL_BAS, TYPE_CONTACT, TYPE_DONNEE) VALUES (1, NULL, NULL, NULL, 3, 6);
